# BinX AI & ML Internship
## Week 2 - Day 3: Linear Algebra for ML

Topics covered:
- Why linear algebra is the language of ML
- Vectors: one sample's features
- Matrices: a full dataset
- The dot product and model prediction
- Matrix multiplication and the shape matching rule

## Linear Algebra for Machine Learning

### What is Linear Algebra for Machine Learning?

Linear Algebra is the branch of mathematics that provides the language used to represent, manipulate, and transform data inside Machine Learning models.

Almost every Machine Learning algorithm works with numbers organized as vectors and matrices. During training and prediction, these mathematical objects are combined through linear algebra operations such as matrix multiplication and dot products.

In simple words:

> **Machine Learning is data, and Linear Algebra is the language used to describe that data.**

---

### Why Does Machine Learning Need Linear Algebra?

Real world data is rarely a single number.

Instead, datasets usually contain thousands or millions of samples, where each sample has many features.

For example, suppose we have a house price dataset.

| House | Area | Bedrooms | Age | Price |
|--------|------|----------|-----|-------|
| 1 | 1800 | 3 | 12 | 250000 |
| 2 | 2200 | 4 | 5 | 340000 |
| 3 | 1500 | 2 | 20 | 180000 |

Each row represents one sample.

Each column represents one feature.

This entire dataset is naturally represented as a **matrix**.

---

### Why Linear Algebra Matters

Linear Algebra is essential because it allows computers to efficiently process huge datasets using mathematical operations.

Without Linear Algebra, modern Machine Learning would not exist.

It is used to:

- Represent datasets
- Store model parameters
- Compute predictions
- Transform data
- Optimize model parameters during training
- Build Deep Learning models

Nearly every ML algorithm relies on Linear Algebra internally.

Examples include:

- Linear Regression
- Logistic Regression
- Support Vector Machines (SVM)
- Principal Component Analysis (PCA)
- Neural Networks
- Deep Learning

---

### Linear Algebra as the Language of Machine Learning

Machine Learning models do not understand words or images directly.

Everything must first be converted into numbers.

Linear Algebra provides the mathematical structures for representing these numbers.

These structures include:

- Scalars
- Vectors
- Matrices
- Tensors

These objects allow ML models to represent:

- Tabular data
- Images
- Audio
- Videos
- Text embeddings

For example:

- A customer can be represented as a vector of features.
- A dataset becomes a matrix.
- A color image becomes a 3D tensor.
- A batch of images becomes a 4D tensor.

---

### Data Representation

Machine Learning usually represents data using four mathematical objects:

| Object | Dimensions | Example | ML Usage |
|---------|------------|----------|----------|
| Scalar | 0D | 5 | Learning rate, bias |
| Vector | 1D | [25, 50000, 3] | One data sample |
| Matrix | 2D | Dataset | Multiple samples |
| Tensor | 3D+ | Images, videos | Deep Learning |

---

### How Linear Algebra is Used in ML

The entire Machine Learning pipeline depends on Linear Algebra.

For example:

Input Data => Vector Representation => Matrix Operations => Dot Products => Prediction => Loss Calculation => Gradient Updates => Improved Model

Almost every step consists of vector and matrix operations.

---

### Real-Life Example

Suppose we want to predict a house price.

**Features:**

- Area
- Bedrooms
- Age

**Feature Vector**

x = [1800, 3, 10]

**Model Weights**

w = [120, 15000, -800]

**Prediction:**

Prediction = x · w + bias

The model multiplies every feature by its weight using the **dot product**, then adds the bias to produce the final prediction.

This simple operation is the foundation of Linear Regression, Logistic Regression, and Neural Networks.

---

### Key Takeaways

- Linear Algebra is the mathematical language of Machine Learning.
- Every dataset is represented as vectors and matrices.
- ML models perform matrix and vector operations to make predictions.
- Dot products and matrix multiplication are among the most important operations.
- Understanding Linear Algebra helps explain how ML algorithms actually work rather than treating them as black boxes.

----------------------------------------------------------------------------------------------------------------------------------------------------------

## 1. Scalars

### What is a Scalar?

A **scalar** is a single numerical value.

Unlike vectors and matrices, a scalar has **magnitude only** and **no direction**.

It is the simplest mathematical object in Linear Algebra.

Examples:

5

3.14

-8

0.25

---

### Scalars in Machine Learning

Scalars appear everywhere in Machine Learning.

Common examples include:

- Learning Rate
- Loss Value
- Accuracy
- Bias
- Regularization Parameter
- Epoch Number

Whenever a model stores or computes a single numeric value, it is usually represented as a scalar.

---

### Scalar Multiplication

One of the most common operations is multiplying every element of a vector or matrix by a scalar.

Example:

k = 3

v = [2, -1, 4]

k × v

=

[6, -3, 12]

Every element is multiplied by the same scalar.

---

### Why is Scalar Multiplication Important?

Scalar multiplication is used to:

- Scale feature values
- Normalize data
- Update model parameters
- Control optimization using the learning rate

During Gradient Descent:

New Weight = Old Weight − Learning Rate × Gradient

Notice that the learning rate is a scalar.

---

### Key Takeaways

- A scalar is a single number.
- Scalars have magnitude only.
- Scalars multiply vectors and matrices.
- Scalars are heavily used during model training.

### Examples:

In [968]:
import numpy as np

# Scalar
k = 3

# Vector
v = np.array([2, -1, 4])

print("Scalar:")
print(k)

print("\nOriginal Vector:")
print(v)

# Scalar multiplication
result = k * v

print("\nAfter Scalar Multiplication:")
print(result)

Scalar:
3

Original Vector:
[ 2 -1  4]

After Scalar Multiplication:
[ 6 -3 12]


In [969]:
import numpy as np

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

scalar = 10

scaled_matrix = scalar * matrix

print("Original Matrix:\n")
print(matrix)

print("\nScaled Matrix:\n")
print(scaled_matrix)

Original Matrix:

[[1 2 3]
 [4 5 6]]

Scaled Matrix:

[[10 20 30]
 [40 50 60]]


In [970]:
import numpy as np

# Feature values
features = np.array([170, 65, 22])

# Normalize features by dividing by 100
normalized = features * 0.01

print("Original Features:")
print(features)

print("\nNormalized Features:")
print(normalized)

Original Features:
[170  65  22]

Normalized Features:
[1.7  0.65 0.22]


> **Note:**
 In the previous example, we used **0.01** as a scalar to scale down the feature values. This idea is widely used in **Feature Scaling** and **Normalization** to bring features to similar ranges, helping Machine Learning algorithms train faster, converge more efficiently, and achieve more stable performance.

-----------------------------------------------------------------------------------------------------------------------------------------------------------

## 2. Vectors

### What is a Vector?

A **vector** is an ordered collection of numbers arranged in a single row or a single column.

In Machine Learning, a vector usually represents **one data sample** and all of its features.

For example, suppose we have a customer with the following information:

- Age = 25
- Annual Income = 50,000
- Years as Customer = 3

This customer can be represented as a feature vector:

x = [25, 50000, 3]

Each value inside the vector is called a **feature**.

---

### Why Are Vectors Important?

Vectors are one of the most fundamental data structures in Machine Learning.

Almost every ML model receives a vector as its input.

Examples:

- One house → one vector
- One customer → one vector
- One patient → one vector
- One image (after flattening) → one large vector

Without vectors, models cannot process data.

---

### Vector Dimensions

The number of elements inside a vector is called its **dimension**.

Example:

x = [25, 50000, 3]

This vector contains **3 elements**, so it is called a **3-dimensional vector (3D vector).**

Examples:

[5] → 1D vector

[5, 7] → 2D vector

[5, 7, 9] → 3D vector

[5, 7, 9, 12] → 4D vector

The dimension simply equals the number of features.

---

### Vectors in Machine Learning

Suppose we are predicting house prices.

A single house has:

- Area
- Bedrooms
- Age
- Distance from City Center

The feature vector becomes:

x = [1800, 3, 12, 5]

where:

- 1800 → Area
- 3 → Bedrooms
- 12 → House Age
- 5 → Distance from City Center

One sample = One vector.

---

### Row Vector vs Column Vector

Vectors can be written in two forms.

***Row Vector** 

x = [25, 50000, 3]

**Column Vector**

[
25
50000
3
]

Both represent the same information.

In Machine Learning, row vectors are commonly used when representing datasets, while column vectors are often used in mathematical derivations and matrix operations.

---

### Common Vector Operations

Some basic operations include:

- Vector Addition
- Vector Subtraction
- Scalar Multiplication
- Dot Product (covered next)

These operations are the foundation of many Machine Learning algorithms.

---

### Key Takeaways

- A vector is an ordered list of numbers.
- A vector usually represents one data sample.
- Each value in the vector is a feature.
- The number of elements equals the vector's dimension.
- Every Machine Learning model receives vectors as input.

-----------------------------------------------------------------------

### Practical Example 1 — Creating Vectors

In [971]:
import numpy as np

# Customer feature vector
customer = np.array([25, 50000, 3])

print("Customer Vector:")
print(customer)

print("\nShape:")
print(customer.shape)

print("\nDimensions:")
print(customer.ndim)

print("\nNumber of Features:")
print(customer.size)

Customer Vector:
[   25 50000     3]

Shape:
(3,)

Dimensions:
1

Number of Features:
3


### Practical Example 2 — Accessing Vector Elements

In [972]:
import numpy as np

customer = np.array([25, 50000, 3])

print("Age:", customer[0])
print("Income:", customer[1])
print("Years as Customer:", customer[2])

Age: 25
Income: 50000
Years as Customer: 3


### Practical Example 3 — Vector Addition

In [973]:
import numpy as np

v1 = np.array([2, 4, 6])
v2 = np.array([1, 3, 5])

result = v1 + v2

print("Vector 1:", v1)
print("Vector 2:", v2)
print("Addition:", result)

Vector 1: [2 4 6]
Vector 2: [1 3 5]
Addition: [ 3  7 11]


### Practical Example 4 — Vector Subtraction

In [974]:
import numpy as np

v1 = np.array([10, 8, 6])
v2 = np.array([3, 2, 1])

result = v1 - v2

print("Vector 1:", v1)
print("Vector 2:", v2)

print("Subtraction: ",result)

Vector 1: [10  8  6]
Vector 2: [3 2 1]
Subtraction:  [7 6 5]


### Practical Example 5 — Feature Vector in Machine Learning

In [975]:
import numpy as np

house = np.array([
    1800,  # Area (sq ft)
    3,     # Bedrooms
    12,    # Age
    5      # Distance from city (km)
])

feature_names = ["Area", "Bedrooms", "Age", "Distance"]

print("House Features:\n")

for name, value in zip(feature_names, house):
    print(f"{name}: {value}")

House Features:

Area: 1800
Bedrooms: 3
Age: 12
Distance: 5


> **Note:** 
In most Machine Learning algorithms, the model does not process the entire dataset as a table at once. Instead, it processes **one row (sample) at a time**, where each row is represented as a **feature vector**. Mathematical operations, such as the **dot product** with the model's weights, are then performed to generate a prediction.
>
> **In other words:**
>
> **One Row in the Dataset = One Feature Vector = One Input to the Machine Learning Model**

------------------------------------------------------------------------------------------------------

## 3. Matrices

### What is a Matrix?

A **matrix** is a two-dimensional array of numbers organized into **rows** and **columns**.

In Machine Learning, a matrix usually represents an entire dataset.

- Each **row** represents one sample (observation).
- Each **column** represents one feature (variable).

A matrix is simply a collection of vectors stacked together.

---

### Matrix Representation

Suppose we have information about three customers.

| Age | Income | Years as Customer |
|------|---------|-------------------|
| 25 | 50000 | 3 |
| 40 | 80000 | 10 |
| 33 | 62000 | 5 |

This dataset can be represented as:

X =

[
25   50000    3
40   80000   10
33   62000    5
]

This is called the **feature matrix**.

---

### Matrix Shape

The size of a matrix is described by its **shape**.

Shape = (rows, columns)

For the previous example:

Rows = 3

Columns = 3

Shape = (3,3)

Meaning:

- 3 samples
- 3 features

---

### Rows vs Columns

Each **row** is one complete data sample.

Each **column** represents one feature across all samples.

Example:

Row 1

[25, 50000, 3]

↓

Customer 1

Column 2

[50000, 80000, 62000]

↓

Income feature

---

### Why Are Matrices Important?

Almost every Machine Learning dataset is stored as a matrix.

Examples:

- House Price Dataset
- Customer Dataset
- Medical Dataset
- Student Dataset

The feature matrix is commonly denoted as **X**.

Models receive **X** as input during training and prediction.

---

### Matrix Dimensions in ML

Suppose:

1000 customers

5 features

Then

Matrix Shape

(1000, 5)

Meaning:

- 1000 samples
- 5 input features

The number of rows is always the number of samples.

The number of columns is always the number of features.

---

### Matrix vs Vector

| Vector | Matrix |
|---------|---------|
| One-dimensional | Two-dimensional |
| Represents one sample | Represents the entire dataset |
| Shape: (n,) | Shape: (m, n) |

---

### Key Takeaways

- A matrix is a collection of vectors.
- Rows represent samples.
- Columns represent features.
- Every ML dataset is usually stored as a matrix.
- Matrix operations make Machine Learning efficient.

----------------

### Practical Example 1 — Creating a Matrix

In [976]:
import numpy as np

# Dataset
X = np.array([
    [25, 50000, 3],
    [40, 80000, 10],
    [33, 62000, 5]
])

print("Dataset Matrix:")
print(X)

Dataset Matrix:
[[   25 50000     3]
 [   40 80000    10]
 [   33 62000     5]]


### Practical Example 2 — Matrix Shape

In [977]:
import numpy as np

X = np.array([
    [25, 50000, 3],
    [40, 80000, 10],
    [33, 62000, 5]
])

print("Shape:", X.shape)
print("Dimensions:", X.ndim)
print("Rows:", X.shape[0])
print("Columns:", X.shape[1])

Shape: (3, 3)
Dimensions: 2
Rows: 3
Columns: 3


### Practical Example 3 — Accessing Rows and Columns

In [978]:
import numpy as np

X = np.array([
    [25, 50000, 3],
    [40, 80000, 10],
    [33, 62000, 5]
])

print("First Sample:")
print(X[0])

print("\nIncome Column:")
print(X[:, 1])

First Sample:
[   25 50000     3]

Income Column:
[50000 80000 62000]


### Practical Example 4 — Matrix Slicing

In [979]:
import numpy as np

X = np.array([
    [25, 50000, 3],
    [40, 80000, 10],
    [33, 62000, 5]
])

print("First Two Samples:")
print(X[:2])

print("\nFirst Two Features:")
print(X[:, :2])

First Two Samples:
[[   25 50000     3]
 [   40 80000    10]]

First Two Features:
[[   25 50000]
 [   40 80000]
 [   33 62000]]


### Practical Example 5 — Matrix in a Real ML Scenario

In [980]:
import numpy as np

# House dataset
houses = np.array([
    [1800, 3, 12],
    [2200, 4, 5],
    [1500, 2, 20],
    [2000, 3, 8]
])

print("Dataset Shape:", houses.shape)

print("\nNumber of Houses:", houses.shape[0])

print("Number of Features:", houses.shape[1])

print("\nDataset:")
print(houses)

Dataset Shape: (4, 3)

Number of Houses: 4
Number of Features: 3

Dataset:
[[1800    3   12]
 [2200    4    5]
 [1500    2   20]
 [2000    3    8]]


----

## Dot Product

### What is a Dot Product?

The **dot product** (also called scalar product) is an operation between two vectors that produces a single numerical value.

It works by:

1. Multiplying corresponding elements of two vectors.
2. Adding all the resulting values together.

The result is always a **scalar**.

Mathematically:

$$
a \cdot b = a_1b_1 + a_2b_2 + ... + a_nb_n
$$

Where:

- `a` and `b` are vectors.
- Each element in the first vector is multiplied by the corresponding element in the second vector.
- The products are summed to produce one number.

---

### Intuition Behind Dot Product

Think about a machine learning model predicting a value.

Each feature has:

- A value (input feature)
- An importance value (weight)

The dot product combines: **Feature values × Feature importance**


into one final score.

For example:

A house prediction model:

Features:

- Size = 150 m²
- Bedrooms = 3
- Age = 10 years

Weights:

- Size importance
- Bedroom importance
- Age importance

The model calculates: **Prediction = Features · Weights**


This is exactly the idea behind linear models.



---

### Mathematical Example

Suppose we have two vectors:

$$
a = [2,3,4]
$$

$$
b = [10,20,30]
$$


The dot product is calculated by multiplying corresponding elements and adding the results:

$$
a \cdot b = (2 \times 10) + (3 \times 20) + (4 \times 30)
$$


Step by step:

$$
= 20 + 60 + 120
$$


Finally:

$$
= 200
$$


Therefore:

$$
a \cdot b = 200
$$


The result of the dot product is a **single scalar value**.

---

### Python Implementation Without NumPy

In [981]:
vector_a = [2, 3, 4]
vector_b = [10, 20, 30]

dot_product = 0

for i in range(len(vector_a)):
    dot_product += vector_a[i] * vector_b[i]

print(dot_product)

200


### Using NumPy

NumPy provides a direct function:
- np.dot()
- @ operator

Both calculate dot products efficiently.

In [982]:
import numpy as np

a = np.array([2,3,4])
b = np.array([10,20,30])

result = np.dot(a,b)

print(result)

200


In [983]:
result = a @ b

print(result)

200


---

### Dot Product in ML Models

Machine learning models represent predictions as mathematical operations.

A simple linear model:

$$
prediction = features \cdot weights + bias
$$


The dot product calculates how much each feature contributes to the final prediction.

Large positive weights increase the prediction.

Negative weights decrease the prediction.

Therefore, understanding dot products means understanding how many ML models make predictions internally.

#### Linear Regression Example


$$
y = Xw + b
$$

Where:

- **X** → Input features  
- **w** → Model weights  
- **b** → Bias term  
- **y** → Final prediction  

#### Understanding Xw

The most important part of the equation is:

$$
Xw
$$

This represents the **dot product** between:

- Feature values
- Model weights

The dot product combines the contribution of every feature into one final score.



---

### Practical ML Example

Let's predict a customer's score:

**Features:**

- Age = 25
- Income = 50000
- Experience = 3

**Weights:**

- Age weight = 0.1
- Income weight = 0.0002
- Experience weight = 1.5

In [984]:
import numpy as np

features = np.array([25,50000,3])

weights = np.array([0.1,0.0002,1.5])


prediction = np.dot(features, weights)

print("Features : ",features)
print("Weights : " , weights)
print("prediction",prediction)

Features :  [   25 50000     3]
Weights :  [1.0e-01 2.0e-04 1.5e+00]
prediction 17.0


**Manual Verification**

In [985]:
calculation = (
    25*0.1 +
    50000*0.0002 +
    3*1.5
)

print(calculation)

17.0


---

### Why Dot Product is Important?

Dot products appear everywhere in Machine Learning:

**Linear Regression**
Prediction:

$$
y = Xw+b
$$


**Logistic Regression**

The probability is calculated from:

$$
z = Xw+b
$$


**Neural Networks**

Every neuron performs:

$$
output = weights \cdot inputs + bias
$$

**Deep Learning**

Matrix multiplication is basically many dot products performed together.

---

### Common Mistake 
Vector Size Must Match

**Correct:**

In [986]:
a = np.array([1,2,3])

b = np.array([4,5,6])

print(np.dot(a,b))

32


**Wrong:**

In [987]:
a = np.array([1,2,3])

b = np.array([4,5])

np.dot(a,b)

ValueError: shapes (3,) and (2,) not aligned: 3 (dim 0) != 2 (dim 0)

---

## Matrix Multiplication 

### Why Matrix Multiplication Matters in Machine Learning

In the previous section, we learned that a single machine learning prediction is created using a dot product:

prediction = features · weights + bias

The dot product works for **one sample**.

However, real machine learning datasets contain thousands or millions of samples.

Instead of calculating predictions one sample at a time, ML models use **matrix multiplication** to calculate predictions for all samples simultaneously.

Matrix multiplication is essentially a **batch of dot products**.

It allows the model to process an entire dataset in one optimized operation.

**A single sample is represented as a vector.**

Example:

A customer has three features:

- Age
- Income
- Years of subscription

The sample can be represented as:

[Age, Income, Years]

In [ ]:
import numpy as np

customer = np.array([25, 50000, 3])

print(customer)

The model has learned weights that represent the importance of each feature.

Each feature is multiplied by its corresponding weight.

Example:

Age weight → 0.1  
Income weight → 0.0002  
Years weight → 1.5

In [ ]:
weights = np.array([0.1, 0.0002, 1.5])

print(weights)

The dot product multiplies corresponding elements and sums the results.

Example:

features · weights

=

(age × age_weight)
+
(income × income_weight)
+
(years × years_weight)

The result is one prediction value.

In [ ]:
prediction = np.dot(customer, weights)

print(prediction)

**The Problem with Many Samples**

Imagine we have thousands of customers.

Dataset:

Customer 1 → [25, 50000, 3]

Customer 2 → [40, 80000, 10]

Customer 3 → [33, 62000, 5]


We cannot manually calculate:

customer1 · weights

customer2 · weights

customer3 · weights


Machine learning solves this using matrix multiplication.

### Representing Dataset as a Matrix

A dataset is represented as a matrix.

Rows = samples

Columns = features


Example:

3 customers × 3 features

Shape:

(samples, features)
=
(3,3)

In [ ]:
X = np.array([
    [25, 50000, 3],
    [40, 80000, 10],
    [33, 62000, 5]
])


print(X)

print("Shape:", X.shape)

[[   25 50000     3]
 [   40 80000    10]
 [   33 62000     5]]
Shape: (3, 3)


## Matrix Multiplication Idea

### Step-by-Step Matrix Multiplication Example

**Given Matrices**

Suppose we have two matrices:

$$
A =
\begin{bmatrix}
3 & 1 & 2 \\
2 & 0 & 4
\end{bmatrix}
$$


$$
B =
\begin{bmatrix}
2 & 5 \\
4 & 1 \\
7 & 3
\end{bmatrix}
$$


We want to calculate:

$$
AB = A \times B
$$

---

### Matrix Multiplication Rule

To calculate each element in the result matrix:

1. Take a **row from Matrix A**
2. Take a **column from Matrix B**
3. Multiply corresponding values
4. Add the results together

This operation is exactly a **Dot Product**.

---

### Step 1: Calculate the Shape of the Result

Matrix A:

$$
A =
\begin{bmatrix}
3 & 1 & 2 \\
2 & 0 & 4
\end{bmatrix}
$$

Shape:

$$
(2,3)
$$

Meaning:

- 2 rows
- 3 columns


Matrix B:

$$
B =
\begin{bmatrix}
2 & 5 \\
4 & 1 \\
7 & 3
\end{bmatrix}
$$

Shape:

$$
(3,2)
$$

Meaning:

- 3 rows
- 2 columns


The inner dimensions must match:

$$
(2,\mathbf{3}) \times (\mathbf{3},2)
$$


Therefore, the result shape is:

$$
(2,2)
$$


The output matrix will have:

- 2 rows
- 2 columns

---

### Step 2: Calculate First Element

We want:

$$
AB_{11}
$$

Take:

First row from A:

$$
[3,1,2]
$$


First column from B:

$$
\begin{bmatrix}
2\\
4\\
7
\end{bmatrix}
$$


Calculate the dot product:

$$
(3 \times 2)+(1 \times 4)+(2 \times 7)
$$


$$
=6+4+14
$$


$$
=24
$$


Therefore:

$$
AB_{11}=24
$$


---

### Step 3: Calculate Second Element in First Row

We want:

$$
AB_{12}
$$


Take:

First row from A:

$$
[3,1,2]
$$


Second column from B:

$$
\begin{bmatrix}
5\\
1\\
3
\end{bmatrix}
$$


Calculate:

$$
(3 \times 5)+(1 \times 1)+(2 \times 3)
$$


$$
=15+1+6
$$


$$
=22
$$


Therefore:

$$
AB_{12}=22
$$


The first row of the result is:

$$
[24,22]
$$


---

### Step 4: Calculate First Element in Second Row

We want:

$$
AB_{21}
$$


Take:

Second row from A:

$$
[2,0,4]
$$


First column from B:

$$
\begin{bmatrix}
2\\
4\\
7
\end{bmatrix}
$$


Calculate:

$$
(2 \times 2)+(0 \times 4)+(4 \times 7)
$$


$$
=4+0+28
$$


$$
=32
$$


Therefore:

$$
AB_{21}=32
$$


---

### Step 5: Calculate Second Element in Second Row

We want:

$$
AB_{22}
$$


Take:

Second row from A:

$$
[2,0,4]
$$


Second column from B:

$$
\begin{bmatrix}
5\\
1\\
3
\end{bmatrix}
$$


Calculate:

$$
(2 \times 5)+(0 \times 1)+(4 \times 3)
$$


$$
=10+0+12
$$


$$
=22
$$


Therefore:

$$
AB_{22}=22
$$


---

### Final Result

After calculating all elements:

$$
AB =
\begin{bmatrix}
24 & 22 \\
32 & 22
\end{bmatrix}
$$


---

### Matrix Multiplication Intuition 

Matrix multiplication is simply many dot products happening together.

Each cell in the output matrix represents:

$$
\text{Row of A} \cdot \text{Column of B}
$$


For example:

The first value:

$$
AB_{11}
$$

is:

$$
\text{First row of A} \cdot \text{First column of B}
$$


---

### Matrix Multiplication in Machine Learning 

In Machine Learning:

$$
XW
$$

is a matrix multiplication.

Where:

- $X$ → Input feature matrix
- $W$ → Model weights
- Output → Predictions


Instead of calculating one sample manually, the model performs many dot products simultaneously for thousands or millions of samples.

This is why matrix multiplication is one of the most important operations in Machine Learning.





**Matrix Multiplication Using NumPy**

In [ ]:
w = np.array([0.1, 0.0002, 1.5])


predictions = X @ w


print(predictions)

[17.  35.  23.2]


### Matrix Multiplication Shape Rule

For multiplication:

(A × B)

The inner dimensions must match.


Example:

(3 × 3) @ (3)

is valid.


Because:

First matrix columns = 3

Second matrix size = 3


Result:

(3)

---
If the dimensions do not match, multiplication is impossible.

Example:

X:

(3,3)

wrong_weights:

(2,)

The number of features does not match.

In [ ]:
wrong_weights = np.array([0.1,0.2])


X @ wrong_weights

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

---


### Matrix Multiplication Inside Machine Learning Models

Almost every ML model uses matrix operations internally.

Examples:

**Linear Regression**

Prediction:

y = Xw + b


**Logistic Regression**

Probability:

z = Xw + b


**Neural Networks**

Each layer:

output = input × weights + bias


The reason ML frameworks are extremely fast is because they perform these operations using optimized matrix multiplication.

---

### Difference Between Dot Product and Matrix Multiplication

| Operation | Input | Output | ML Meaning |
|-----------|-------|--------|------------|
| Dot Product | One vector + weights | One number | Prediction for one sample |
| Matrix Multiplication | Dataset matrix + weights | Many numbers | Predictions for all samples |

---

### Complete ML Example

In [ ]:
import numpy as np


# Dataset
X = np.array([
    [25, 50000, 3],
    [40, 80000, 10],
    [33, 62000, 5]
])


# Model weights
weights = np.array([
    0.1,
    0.0002,
    1.5
])


# Predictions for all samples
predictions = X @ weights


print("Predictions:")
print(predictions)

Predictions:
[17.  35.  23.2]


### Key Takeaways

- A vector represents one ML sample.
- A matrix represents the whole dataset.
- Dot product creates one prediction.
- Matrix multiplication performs many dot products at once.
- X @ w is the mathematical operation behind many ML predictions.
- Shape compatibility is critical in machine learning.
- Understanding matrix multiplication makes models like Linear Regression, Logistic Regression, and Neural Networks much easier to understand.