# Week 2 - Day 3 - Hands On Lab
Vectors, Matrices & Predictions

### Import NumPy

In [1]:
import numpy as np

### Step 1: 
Represent three data samples as a (3 × features) NumPy matrix.

In [2]:
# Three samples
X = np.array([
    [25, 50000, 3],
    [40, 80000, 10],
    [33, 62000, 5]
])

print(X)

print("Shape:", X.shape)

[[   25 50000     3]
 [   40 80000    10]
 [   33 62000     5]]
Shape: (3, 3)


### Step 2: 
Compute the dot product of one sample vector with a weight vector by hand, then verify it with
np.dot.


**Create Weight Vector**

In [3]:
# Model weights
weights = np.array([
    0.1,
    0.0002,
    1.5
])

print(weights)

print("Shape:", weights.shape)

[1.0e-01 2.0e-04 1.5e+00]
Shape: (3,)


**Dot Product Manually**

In [4]:
sample = X[0]

manual_prediction = (
    sample[0] * weights[0]
    +
    sample[1] * weights[1]
    +
    sample[2] * weights[2]
)

manual_prediction

np.float64(17.0)

**Verify using NumPy**

In [5]:
numpy_prediction = np.dot(sample, weights)

numpy_prediction

np.float64(17.0)

### Step 3: 
Use matrix multiplication (@) to produce a prediction for all three samples at once.

In [6]:
predictions = X @ weights

predictions

array([17. , 35. , 23.2])

### Step 4: 
Deliberately create a shape-mismatch error, read the message, and explain in Markdown why it
occurred and how to fix it.


In [7]:
wrong_weights = np.array([
    0.1,
    0.0002
])

X @ wrong_weights

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

**Understanding Shape Errors**

The matrix:

X

has shape:

(3,3)

meaning:

3 samples
3 features


The weights vector must contain:

3 values

because every feature needs one weight.


Using only 2 weights creates a mismatch:

(3,3) @ (2,)


The inner dimensions do not match.

Correct:

(3,3) @ (3,)

**Fix the Error**

In [ ]:
correct_weights = np.array([
    0.1,
    0.0002,
    1.5
])


X @ correct_weights

array([17. , 35. , 23.2])