# BinX AI & ML Internship
## Day 3 - NumPy: Numerical Computing

Topics covered:
- Why NumPy matters
- Creating arrays
- Array attributes, indexing & slicing
- Vectorized operations
- Broadcasting

### Step 1: What is a Library? Introduction to NumPy

Before diving into NumPy itself, I documented why libraries exist in the 
first place.

**Core Python vs. real-world problems:** Core Python features (variables, 
loops, conditions, lists) are enough for simple programs, but they fall 
short for advanced tasks like working with large datasets, heavy numerical 
computation, or building ML/AI systems. Writing all of that logic from 
scratch would be slow and inefficient.

**What is a library?** A library is a collection of pre-written, tested, 
and optimized code created by experts, which we can reuse instead of 
building everything ourselves. Importing a library gives access to 
powerful tools with far fewer lines of code.

**NumPy specifically:** NumPy (Numerical Python) was created in 2005 by 
Travis Oliphant and is open source. Its core data structure is the 
`ndarray` (N-dimensional array), which stores elements of a single data 
type. Two things make NumPy fast:
- It stores data in **contiguous memory locations**, unlike Python lists, 
  which allows faster access.
- Many of its operations are implemented in **C** internally, rather than 
  pure Python, which is why operations run on the whole array at once 
  without needing explicit loops.

This is why NumPy is considered the numerical backbone of Data Science, 
Machine Learning, and AI libraries - Pandas, Scikit-learn, TensorFlow, 
and PyTorch are all built on top of it.

In [670]:
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.4.6


### Step 2: What is an ndarray?

An **ndarray** (N-dimensional array) is NumPy's core data structure - a 
container built specifically to store numerical values efficiently and 
allow fast math operations on them. Unlike a Python list, it stores data 
in contiguous memory and supports operations written in C internally.

### Step 3: Array Dimensions

Arrays can have different numbers of dimensions:
- **0D (scalar):** a single value, no rows or columns
- **1D (vector):** a plain sequence of numbers
- **2D (matrix):** organized into rows and columns
- **3D+ (tensor):** used later for images/deep learning data

In [671]:
import numpy as np

# Create a scalar, vector, matrix, and tensor using NumPy
scalar = np.array(14)
print("Scalar:", scalar)

vector = np.array([1, 2, 3])
print("Vector:", vector)

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix:\n", matrix)

tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Tensor:\n", tensor)

Scalar: 14
Vector: [1 2 3]
Matrix:
 [[1 2 3]
 [4 5 6]]
Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Step 4: `ndim` - Number of Dimensions

The `.ndim` attribute tells us how many dimensions an array has - whether 
it's a scalar (0), a vector (1), or a matrix (2).

In [672]:
# Check how many dimensions each array has
print("scalar.ndim:", scalar.ndim)
print("vector.ndim:", vector.ndim)
print("matrix.ndim:", matrix.ndim)

scalar.ndim: 0
vector.ndim: 1
matrix.ndim: 2


### Step 5: `shape` - Shape of the Array

The `.shape` attribute returns a tuple showing the size of the array in 
each dimension: `(elements,)` for 1D, `(rows, columns)` for 2D.

In [673]:
# Check the shape of the vector (1D) - just the number of elements
print("vector.shape:", vector.shape)

# Check the shape of the matrix (2D) - (rows, columns)
print("matrix.shape:", matrix.shape)

vector.shape: (3,)
matrix.shape: (2, 3)


### Step 6: `size` - Total Number of Elements

The `.size` attribute returns the total count of elements in the array, 
regardless of how many dimensions it has.

In [674]:
# Total number of elements, regardless of shape
print("vector.size:", vector.size)
print("matrix.size:", matrix.size)

vector.size: 3
matrix.size: 6


### Step 7: `dtype` - Data Type

The `.dtype` attribute shows the data type of the elements inside the 
array. All elements in a NumPy array must share the same type - if mixed 
types are given, NumPy automatically converts everything to one 
compatible type (int -> float -> string).

In [675]:
# All integers -> stays as int
x_int = np.array([1, 2, 3])
print("x_int.dtype:", x_int.dtype)

# A float is present -> everything gets converted to float
y_float = np.array([1, 2.5, 3])
print("y_float.dtype:", y_float.dtype)

# A string is present -> everything gets converted to string
z_str = np.array([1, 2.5, "hello"])
print("z_str.dtype:", z_str.dtype)
print("z_str:", z_str)

x_int.dtype: int64
y_float.dtype: float64
z_str.dtype: <U32
z_str: ['1' '2.5' 'hello']


### Step 8: Random Number Generation

`np.random.rand(n)` generates `n` random values between 0 and 1 (uniform 
distribution). `np.random.randn(n)` generates `n` random values from a 
normal distribution (mean 0, values can be negative or positive).

In [676]:
# Generate 5 random numbers between 0 and 1 (uniform distribution)
uniform_random = np.random.rand(5)
print(uniform_random)

# Generate 5 random numbers from a normal distribution (mean=0, std=1)
normal_random = np.random.randn(5)
print(normal_random)

[0.86354185 0.74712164 0.55624023 0.13645523 0.05991769]
[ 1.2245077  -0.23817737 -0.34082828  0.48759421  1.73907303]


### Step 9: `np.arange` - Creating Sequences

`np.arange(start, stop, step)` works just like Python's built-in `range`, 
but returns a NumPy array instead of a list.

In [677]:
# Numbers from -10 up to (but not including) 10, stepping by 2
sequence = np.arange(-10, 10, 2)
print(sequence)

[-10  -8  -6  -4  -2   0   2   4   6   8]


### Step 10: `reshape` - Changing the Array's Shape

`.reshape(rows, columns)` rearranges the same data into a new shape, 
without changing any values. The total number of elements must stay the 
same before and after.

In [678]:
# A flat 1D array with 12 elements
flat = np.arange(12)
print("Before reshape:", flat)

# Reshape into 3 rows and 4 columns (3 x 4 = 12, so it works)
reshaped = flat.reshape(3, 4)
print("After reshape:")
print(reshaped)

Before reshape: [ 0  1  2  3  4  5  6  7  8  9 10 11]
After reshape:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### Step 11: `linspace` and `logspace`

`np.linspace(start, stop, num)` creates `num` evenly spaced values between 
`start` and `stop`. `np.logspace(start, stop, num)` does the same, but on 
a logarithmic scale (useful for scientific calculations).

In [679]:
# 10 evenly spaced values between 0 and 1
linear_values = np.linspace(0, 1, 10)
print(linear_values)

# 7 values evenly spaced on a logarithmic scale, from 10^-3 to 10^3
log_values = np.logspace(-3, 3, 7)
print(log_values)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[1.e-03 1.e-02 1.e-01 1.e+00 1.e+01 1.e+02 1.e+03]


### Step 12: Special Matrices

`np.zeros((rows, cols))` creates a matrix filled with zeros. `np.ones((rows, cols))` 
creates a matrix filled with ones. `np.eye(n)` creates an identity matrix 
(1s on the diagonal, 0s elsewhere) - commonly used in linear algebra.

In [680]:
# A 2x3 matrix filled entirely with zeros
zeros_matrix = np.zeros((2, 3))
print(zeros_matrix)

# A 3x2 matrix filled entirely with ones
ones_matrix = np.ones((3, 2))
print(ones_matrix)

# A 3x3 identity matrix - 1s on the diagonal, 0s everywhere else
identity_matrix = np.eye(3)
print(identity_matrix)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Examples and notes for a complete review
Creating ndarray

An ndarray can be created from a list or a tuple object as shown in the examples below. It is possible to create a 1-dimensional or multi-dimensional array from the list objects as well as tuples.

In [681]:
import numpy as np

oneDim = np.array([1.0,2,3,4,5])   # a 1-dimensional array (vector)
print(oneDim)
print("#Dimensions =", oneDim.ndim)
print("Dimension =", oneDim.shape)
print("Size =", oneDim.size)
print("Array type =", oneDim.dtype, '\n')

twoDim = np.array([[1,2],[3,4],[5,6],[7,8]])  # a two-dimensional array (matrix)
print(twoDim)
print("#Dimensions =", twoDim.ndim)
print("Dimension =", twoDim.shape)
print("Size =", twoDim.size)
print("Array type =", twoDim.dtype, '\n')

arrFromTuple = np.array([(1,'a',3.0),(2,'b',3.5)])  # create ndarray from tuple
print(arrFromTuple)
print("#Dimensions =", arrFromTuple.ndim)
print("Dimension =", arrFromTuple.shape)
print("Size =", arrFromTuple.size)
print("Array type =", arrFromTuple.dtype, '\n')

[1. 2. 3. 4. 5.]
#Dimensions = 1
Dimension = (5,)
Size = 5
Array type = float64 

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
#Dimensions = 2
Dimension = (4, 2)
Size = 8
Array type = int64 

[['1' 'a' '3.0']
 ['2' 'b' '3.5']]
#Dimensions = 2
Dimension = (2, 3)
Size = 6
Array type = <U32 



There are also built in functions available in numpy to create the ndarrays & Special Matrices. 

In [682]:
print('Array of random numbers from a uniform distribution')
print(np.random.rand(5))      # random numbers from a uniform distribution between [0,1]

print('\nArray of random numbers from a normal distribution')
print(np.random.randn(5))     # random numbers from a normal distribution

print('\nArray of integers between -10 and 10, with step size of 2')
print(np.arange(-10,10,2))    # similar to range, but returns ndarray instead of list

print('\n2-dimensional array of integers from 0 to 11')
print(np.arange(12).reshape(3,4))  # reshape to a matrix

print('\nArray of values between 0 and 1, split into 10 equally spaced values')
print(np.linspace(0,1,10))    # split interval [0,1] into 10 equally separated values

print('\nArray of values from 10^-3 to 10^3')
print(np.logspace(-3,3,7))    # create ndarray with values from 10^-3 to 10^3

# Special Matrices

print('A 2 x 3 matrix of zeros')
print(np.zeros((2,3)))        # a matrix of zeros

print('\nA 3 x 2 matrix of ones')
print(np.ones((3,2)))         # a matrix of ones

print('\nA 3 x 3 identity matrix')
print(np.eye(3))              # a 3 x 3 identity matrix

Array of random numbers from a uniform distribution
[0.01255598 0.07197428 0.96727633 0.56810046 0.20329323]

Array of random numbers from a normal distribution
[ 0.84616065 -0.85951594  0.35054598 -1.31228341 -0.03869551]

Array of integers between -10 and 10, with step size of 2
[-10  -8  -6  -4  -2   0   2   4   6   8]

2-dimensional array of integers from 0 to 11
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Array of values between 0 and 1, split into 10 equally spaced values
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]

Array of values from 10^-3 to 10^3
[1.e-03 1.e-02 1.e-01 1.e+00 1.e+01 1.e+02 1.e+03]
A 2 x 3 matrix of zeros
[[0. 0. 0.]
 [0. 0. 0.]]

A 3 x 2 matrix of ones
[[1. 1.]
 [1. 1.]
 [1. 1.]]

A 3 x 3 identity matrix
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Step 13: What Does "Element-wise" Mean?

"Element-wise" means an operation is applied separately to every element 
inside the array, not to the array as one single object. For example, 
`x + 1` doesn't add 1 to the array as a whole - it adds 1 to each element 
individually. This is what makes NumPy operations so fast: no loop is 
needed.

### Step 14: Element-wise Operations (Array + Scalar)

When an operation is performed between an array and a single number 
(a scalar), NumPy applies that operation to every element of the array.

In [683]:
x = np.array([1, 2, 3, 4, 5])
print("x =", x)

# Add 1 to every element
print("x + 1 =", x + 1)

# Subtract 1 from every element
print("x - 1 =", x - 1)

# Multiply every element by 2
print("x * 2 =", x * 2)

# Integer (floor) division - divide then round down
print("x // 2 =", x // 2)

# Square every element
print("x ** 2 =", x ** 2)

# Remainder after dividing every element by 2
print("x % 2 =", x % 2)

# Divide 1 by every element
print("1 / x =", 1 / x)

x = [1 2 3 4 5]
x + 1 = [2 3 4 5 6]
x - 1 = [0 1 2 3 4]
x * 2 = [ 2  4  6  8 10]
x // 2 = [0 1 1 2 2]
x ** 2 = [ 1  4  9 16 25]
x % 2 = [1 0 1 0 1]
1 / x = [1.         0.5        0.33333333 0.25       0.2       ]


### Step 15: Element-wise Operations (Array + Array)

When operating on two arrays of the same shape, NumPy applies the 
operation position by position: the first element of `x` with the first 
element of `y`, the second with the second, and so on.

In [684]:
x = np.array([2, 4, 6, 8, 10])
y = np.array([1, 2, 3, 4, 5])
print("x =", x)
print("y =", y)

# Each position added together: 2+1, 4+2, 6+3, 8+4, 10+5
print("x + y =", x + y)

print("x - y =", x - y)
print("x * y =", x * y)
print("x / y =", x / y)
print("x // y =", x // y)

# Each element of x raised to the power of the matching element in y
print("x ** y =", x ** y)

x = [ 2  4  6  8 10]
y = [1 2 3 4 5]
x + y = [ 3  6  9 12 15]
x - y = [1 2 3 4 5]
x * y = [ 2  8 18 32 50]
x / y = [2. 2. 2. 2. 2.]
x // y = [2 2 2 2 2]
x ** y = [     2     16    216   4096 100000]


### Step 16: The Same-Shape Rule

For element-wise operations between two arrays, both arrays must have 
compatible shapes - in the simplest case, the exact same shape. If they 
don't match, NumPy raises an error (unless broadcasting rules apply, 
which is a separate, more advanced topic covered later).

In [685]:
a = np.array([1, 2, 3])
b = np.array([1, 2])

# This will raise an error because the shapes (3,) and (2,) don't match
print(a + b)

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

### Step 17: Why This Matters

Element-wise operations are powerful because they:
- Remove the need for explicit loops
- Make code shorter and easier to read
- Run much faster (vectorization)
- Form the foundation of most ML computations (loss functions, gradients, 
  transformations)

### Step 18: Indexing vs. Slicing

**Indexing** means selecting one single element from an array. 
**Slicing** means selecting a range (a subset) of elements. NumPy uses 
zero-based indexing, so the first element is at index `0`, the second at 
index `1`, and so on.

### Step 19: 1D Indexing

`array[index]` accesses a single element at that position. Negative 
indices count from the end of the array (`-1` is the last element).

In [ ]:
x = np.array([10, 20, 30, 40, 50])

# First element (index 0)
print(x[0])

# Third element (index 2)
print(x[2])

# Last element (negative indexing counts from the end)
print(x[-1])

10
30
50


### Step 20: 1D Slicing

`array[start:end]` selects a range of elements: `start` is included, 
`end` is excluded (the slice stops right before it).

In [ ]:
x = np.array([-5, -4, -3, -2, -1, 0, 1, 2, 3, 4])

# start=3 (included), end=5 (excluded) -> gets indices 3 and 4 only
print(x[3:5])

[-2 -1]


### Step 21: Slices are Views, Not Copies

This is the most important NumPy concept in this section. Slicing does 
**not** create a new independent array , it creates a **view**, which 
points to the same underlying memory as the original array. Modifying 
the slice changes the original array too.

In [ ]:
x = np.arange(-5, 5)
print("Before:", x)

# y is a VIEW into x - not a separate copy
y = x[3:5]
print("Slice y:", y)

# Modifying y changes the shared memory...
y[0] = 1000
print("After modifying y:")
print("y:", y)
print("x:", x)   # notice x changed too, even though we only touched y!

Before: [-5 -4 -3 -2 -1  0  1  2  3  4]
Slice y: [-2 -1]
After modifying y:
y: [1000   -1]
x: [  -5   -4   -3 1000   -1    0    1    2    3    4]


### Step 22: Making a Real Copy

To get a slice that is fully independent from the original array (so 
changing it does NOT affect the original), use `.copy()`.

**Key rule:**
- `x[a:b]` → a view (shares memory with the original)
- `x[a:b].copy()` → a real, independent copy

In [ ]:
x = np.arange(-5, 5)

# .copy() creates fully independent data
z = x[3:5].copy()

z[0] = 500
print("x:", x)   # unchanged this time
print("z:", z)   # changed

x: [-5 -4 -3 -2 -1  0  1  2  3  4]
z: [500  -1]


### Step 23: 2D Indexing - Rows and Columns

A 2D array has rows and columns. `array[row_index, column_index]` accesses 
a specific element, while `array[row_index]` alone returns the entire row.

In [ ]:
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# Access an entire row (row index 2 -> the third row)
print(arr[2])

# Access a single element (row 2, column 1)
print(arr[2, 1])

### Step 24: 2D Slicing Using the Colon `:`

The colon `:` means "take all" along that dimension. Combining it with a 
range lets us select a full column, a rectangular sub-matrix, or a range 
of columns across all rows.

In [ ]:
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
# All rows, column 2 only -> a full column
print("Full column:", arr[:, 2])

# First 2 rows, first 2 columns -> a sub-matrix
print("Sub-matrix:")
print(arr[:2, :2])

# All rows, from column 2 to the end -> last two columns
print("Last two columns:")
print(arr[:, 2:])

Full column: [ 3  7 11]
Sub-matrix:
[[1 2]
 [5 6]]
Last two columns:
[[ 3  4]
 [ 7  8]
 [11 12]]


### Step 25: Boolean Indexing (Filtering by a Condition)

Boolean indexing selects elements that satisfy a condition. Writing 
`array[condition]` returns only the elements where the condition is True.

In [ ]:
m = np.arange(1, 13).reshape(3, 4)
print(m)

# Keep only the elements divisible by 3
result = m[m % 3 == 0]
print(result)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 3  6  9 12]


### Step 26: Fancy Indexing - Reordering Rows

Passing a list of indices instead of a single index selects (and 
reorders) multiple rows at once, in whatever order the list specifies.

In [ ]:
m2 = np.arange(1, 13).reshape(4,3)
print("Before rearranging rows:")
print(m2)
# Rearrange the rows of m2 according to the specified indices
indices = [2,1,0,3]
print("After rearranging rows:")
print(m2[indices])

Before rearranging rows:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
After rearranging rows:
[[ 7  8  9]
 [ 4  5  6]
 [ 1  2  3]
 [10 11 12]]


### Step 27: Fancy Indexing - Selecting Specific Elements

Passing two lists together  one for rows, one for columns  selects 
individual elements at each (row, col) pair. This is different from 
reordering whole rows.

In [ ]:
m3 = np.arange(1, 13).reshape(3,4)
print("Before rearranging columns:")
print(m3)
# select (0,0), (1,1), (2,3) -> the elements at these positions will be selected
row_index = [0,1,2] 
col_index = [0,1,3]   
print("After rearranging columns:")
print(m3[row_index , col_index])

Before rearranging columns:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
After rearranging columns:
[ 1  6 12]


### Statistical & Math Functions

NumPy provides built-in mathematical and statistical functions that apply 
to entire arrays at once: `abs`, `sqrt`, `sign`, `exp`, `sort` for 
individual arrays, `add/subtract/multiply/divide/maximum` as function 
forms of the standard operators, and `min/max/mean/std/sum` for summary 
statistics.

In [ ]:
y = np.array([-1.4, 0.4, -3.2, 2.5, 3.4])
print('y =', y)

print('np.abs(y) =', np.abs(y))                # convert to absolute values
print('np.sqrt(abs(y)) =', np.sqrt(np.abs(y))) # square root (needs abs first)
print('np.sign(y) =', np.sign(y))              # -1, 0, or 1 depending on the sign
print('np.exp(y) =', np.exp(y))                # e raised to the power of each element
print('np.sort(y) =', np.sort(y))              # sorted ascending

np.random.seed(42)     # fixes randomness so results are repeatable
x = np.arange(-2, 3)
y2 = np.random.randn(5)
print('x =', x)
print('y2 =', y2)

print('np.add(x,y2) =', np.add(x, y2))             # same as x + y2
print('np.subtract(x,y2) =', np.subtract(x, y2))   # same as x - y2
print('np.multiply(x,y2) =', np.multiply(x, y2))   # same as x * y2
print('np.divide(x,y2) =', np.divide(x, y2))       # same as x / y2
print('np.maximum(x,y2) =', np.maximum(x, y2))     # element-wise max between the two arrays

y3 = np.array([-3.2, -1.4, 0.4, 2.5, 3.4])
print("Min =", np.min(y3))
print("Max =", np.max(y3))
print("Average =", np.mean(y3))
print("Std deviation =", np.std(y3))
print("Sum =", np.sum(y3))

### Linear Algebra Basics

NumPy supports core linear algebra operations: transpose, matrix-vector 
and matrix-matrix multiplication (`.dot()`), matrix inverse, determinant, 
and eigenvalues/eigenvectors. These are the mathematical foundation behind 
algorithms like Linear Regression and PCA, which come later in the 
program.

In [ ]:
np.random.seed(42)
X = np.random.randn(2, 3)                    # a 2x3 random matrix
print('X =\n', X)
print('X.T =\n', X.T)                         # transpose: flips rows and columns

y4 = np.random.randn(3)                       # a random vector of length 3
print('y4 =', y4)

print('Matrix-vector multiplication:')
print('X.dot(y4) =', X.dot(y4))               # (2x3) . (3,) -> a vector of length 2

print('Matrix-matrix product:')
print('X.dot(X.T) =\n', X.dot(X.T))           # (2x3) . (3x2) -> a 2x2 matrix
print('X.T.dot(X) =\n', X.T.dot(X))           # (3x2) . (2x3) -> a 3x3 matrix

np.random.seed(1)
X2 = np.random.randn(5, 3)
C = X2.T.dot(X2)                              # C is a square (3x3) matrix
print('C =\n', C)

invC = np.linalg.inv(C)                       # inverse of C
print('invC =\n', invC)

detC = np.linalg.det(C)                       # determinant of C (a single number)
print('detC =', detC)

S, U = np.linalg.eig(C)                       # eigenvalues (S) and eigenvectors (U)
print('Eigenvalues =', S)
print('Eigenvectors =\n', U)

X =
 [[ 0.49671415 -0.1382643   0.64768854]
 [ 1.52302986 -0.23415337 -0.23413696]]
X.T =
 [[ 0.49671415  1.52302986]
 [-0.1382643  -0.23415337]
 [ 0.64768854 -0.23413696]]
y4 = [ 1.57921282  0.76743473 -0.46947439]
Matrix-vector multiplication:
X.dot(y4) = [0.37423535 2.33541214]
Matrix-matrix product:
X.dot(X.T) =
 [[0.68534241 0.63723771]
 [0.63723771 2.42926786]]
X.T.dot(X) =
 [[ 2.56634489 -0.42530042 -0.03488151]
 [-0.42530042  0.07394482 -0.03472824]
 [-0.03488151 -0.03472824  0.47432056]]
C =
 [[ 7.00026605 -3.49120236  2.31639992]
 [-3.49120236  3.98786959 -5.35908863]
 [ 2.31639992 -5.35908863 11.20744461]]
invC =
 [[0.39441253 0.65958472 0.23387631]
 [0.65958472 1.80464352 0.72660476]
 [0.23387631 0.72660476 0.38833011]]
detC = 40.50073304778821
Eigenvalues = [15.67530452  6.09646829  0.42380744]
Eigenvectors =
 [[-0.40105391  0.85257252  0.3350759 ]
 [ 0.47809706 -0.11720381  0.87045188]
 [-0.78139552 -0.50929693  0.36060736]]


### More Broadcasting Rules & Examples

Broadcasting follows 3 rules:
(1) arrays are compared dimension by dimension 
(2) a smaller array gets "padded" with size-1 dimensions on 
the left
(3) two dimensions are compatible if they're equal OR one of 
them is 1. Here are a few more real-world-style examples.

In [ ]:
# Broadcasting a scalar across a 2D array
a = np.array([[1, 2, 3], [4, 5, 6]])
print("scalar broadcast:\n", a + 10)

# Broadcasting a 1D array across a 2D array (same as before, different numbers)
a1 = np.array([2, 4, 6])
a2 = np.array([[1, 3, 5], [7, 9, 11]])
print("1D + 2D broadcast:\n", a1 + a2)

# Real-world example: applying a per-row correction factor using [:, None]
temp = np.array([[30, 32, 34, 33, 31],
                  [25, 27, 29, 28, 26],
                  [20, 22, 24, 23, 21]])
corr = np.array([1.5, -0.5, 2.0])
# corr[:, None] turns the 1D array into a column, so it broadcasts down each row
print("temperature correction:\n", temp + corr[:, None])

# Real-world example: normalizing data (subtract mean, divide by std) - very common in ML
img = np.array([[100, 120, 130],
                 [90, 110, 140],
                 [80, 100, 120]])
m = img.mean(axis=0)
s = img.std(axis=0)
normalized = (img - m) / s
print("normalized:\n", normalized)

scalar broadcast:
 [[11 12 13]
 [14 15 16]]
1D + 2D broadcast:
 [[ 3  7 11]
 [ 9 13 17]]
temperature correction:
 [[31.5 33.5 35.5 34.5 32.5]
 [24.5 26.5 28.5 27.5 25.5]
 [22.  24.  26.  25.  23. ]]
normalized:
 [[ 1.22474487  1.22474487  0.        ]
 [ 0.          0.          1.22474487]
 [-1.22474487 -1.22474487 -1.22474487]]


### Matrix Multiplication vs. Element-wise Multiplication

`A * B` multiplies matching positions (element-wise). `A @ B` (or 
`np.matmul(A, B)`) performs true matrix multiplication, following linear 
algebra rules. This distinction is critical - Neural Networks, Linear 
Regression, and PCA all rely on matrix multiplication, not element-wise 
multiplication.

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Element-wise: multiplies matching positions only
print("element-wise A*B:\n", A * B)

# True matrix multiplication (the @ operator)
print("matrix mult A@B:\n", A @ B)

# Same result using the function form
print("np.matmul(A,B):\n", np.matmul(A, B))

element-wise A*B:
 [[ 5 12]
 [21 32]]
matrix mult A@B:
 [[19 22]
 [43 50]]
np.matmul(A,B):
 [[19 22]
 [43 50]]


### Flatten and Ravel - Converting 2D to 1D

`.flatten()` and `.ravel()` both convert a multi-dimensional array into a 
1D array. The key difference: `.flatten()` always returns an independent 
copy, while `.ravel()` returns a view when possible (connecting back to 
the view-vs-copy concept from earlier).

In [ ]:
x2d = np.array([[1, 2, 3], [4, 5, 6]])

flat_copy = x2d.flatten()
flat_view = x2d.ravel()
print("flatten:", flat_copy)
print("ravel:", flat_view)

# Modifying the ravel result CAN affect the original (it's often a view)
flat_view[0] = 999
print("after modifying ravel result, x2d:\n", x2d)

flatten: [1 2 3 4 5 6]
ravel: [1 2 3 4 5 6]
after modifying ravel result, x2d:
 [[999   2   3]
 [  4   5   6]]


### The Axis Concept

Many NumPy functions (like `.mean()`, `.sum()`) accept an `axis` 
parameter. `axis=0` operates down each column, while `axis=1` operates 
across each row. This concept reappears constantly in Pandas and ML work.

In [ ]:
data = np.array([[10, 20], [30, 40]])

# axis=0: compute the mean for each COLUMN
print("mean axis=0:", data.mean(axis=0))

# axis=1: compute the mean for each ROW
print("mean axis=1:", data.mean(axis=1))

mean axis=0: [20. 30.]
mean axis=1: [15. 35.]


### Random Seed for Reproducibility

Setting `np.random.seed(n)` makes random number generation repeatable - 
running the same code twice produces the exact same "random" values. 
BinX Tech's own program notes explicitly require fixing a random seed 
wherever randomness is used, so results can be reproduced later.

In [686]:
np.random.seed(42)
print(np.random.rand(3))

# Resetting to the same seed reproduces the exact same values
np.random.seed(42)
print(np.random.rand(3))

[0.37454012 0.95071431 0.73199394]
[0.37454012 0.95071431 0.73199394]
