# Day 3 - Hands-On Lab
NumPy Array Manipulation

Step 1: Create a 2D array of shape (4, 4) filled with values 1-16 and print its shape and dtype.

In [10]:
import numpy as np 

 # Create a 4x4 array with values from 1 to 16
arr = np.arange(1,17).reshape(4,4)
# Print the original array
print(arr)
# print the shape of the array
print("\nShape: " , arr.shape)

# Print array data type
print("\nData type: " , arr.dtype)



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Shape:  (4, 4)

Data type:  int64


Step 2: Use slicing to extract the second column and the last row.

In [11]:
# Extract the second column and the last row
seconed_column = arr[:, 1]

last_row = arr[-1, :]

print("Second column:", seconed_column)
print("Last row:", last_row)

Second column: [ 2  6 10 14]
Last row: [13 14 15 16]


Step 3: Use a boolean mask to select all values greater than the array's mean.

In [12]:
# Calculate the mean of the array
mean_value = arr.mean()
# Filter the array to get values greater than the mean
filtered_arr = arr[arr > mean_value]
print("Mean value:", mean_value)
print("Filtered array (values greater than mean):", filtered_arr)

Mean value: 8.5
Filtered array (values greater than mean): [ 9 10 11 12 13 14 15 16]


Step 4: Add a 1D row array to every row of a 2D array using broadcasting, and verify the result manually.

In [13]:

row = np.array([10, 20, 30, 40])
# Add the row array to evry row of the matrix
result = arr  + row
print (result)

[[11 22 33 44]
 [15 26 37 48]
 [19 30 41 52]
 [23 34 45 56]]
